Repository runejs/server, pull requests merged in 2021-03, with the labels that each got.

#274 add support for variations in npc configs
  data/config/npc-spawns/lumbridge/lumbridge-general.json
  data/config/npcs/generic-humans.json
  src/game-engine/config/npc-config.ts
Labels: enhancement

#275 small fix to get quests to work again
  src/game-engine/config/index.ts
  src/game-engine/world/actor/player/player.ts
Labels: bug

#278 Fixing lint rules around indentation
  .eslintrc.js
  src/game-engine/config/item-config.ts
  src/game-engine/config/music-regions-config.ts
  src/game-engine/game-server.ts
  src/game-engine/world/actor/player/player-data.ts
  src/game-engine/world/actor/player/player.ts
  src/game-engine/world/index.ts
  src/game-engine/world/map/chunk-manager.ts
  src/game-engine/world/map/region.ts
  src/plugins/commands/player-animation-command.plugin.ts
  src/plugins/music/music-tab.plugin.ts
Labels: bug, documentation, game engine, plugins

#277 Making default item variations have no suffix and adding a duplicate …
  data/config/items/barrows/dharoks.json
  data/config/items/food.json
  src/game-engine/config/item-config.ts
  src/game-engine/config/npc-config.ts
Labels: enhancement

#281 Fix quest colors being green when not started
  src/game-engine/world/actor/player/player.ts
Labels: bug
